### PR TITLE
Reload Bundle Assets When Resource Assets Change

### LINKED ISSUE #20: Hot Reloading of Resource Assets
Because resource assets are separate from the Bundle asset, when a resource asset is hot reloaded, it doesn't update the bundle that depends on it. This makes it a little tricky to figure out how to setup hot reloading for it.

We need a system that will watch for ResourceAsset events and then update the corresponding BundleAsset when they change.

I'm going to work on this, but I wanted to open the issue first.

### PR DESCRIPTION
**Pull request by zicklag**
Tested and working!

Closes #20.

### CODE REVIEW

**Comment by zicklag** [comment]
Just a friendly ping @kgv: would this be possible to look at before pushing to crates.io?

**Comment by zicklag** [comment]
Thanks!

Apparently because of the update to Bevy 0.8, some of the code in the PR was broke now that it merged to master. I'll open another PR to fix that real quick.

**Comment by kgv** [comment]
@zicklag thx for helping, sorry for delay

**Comment by zicklag** [comment]
No problem at all, I understand life, time, and priorities. :)

**Pull request merged**
