### PR TITLE
Allow Custom `BundleAsset` Loader Implementations

### PR DESCRIPTION
**Pull request by zicklag**
I'm experimenting with this for my project and I ran into a scenario where I want to be the one to handle the bundle asset loading, because I use YAML for all my assets and I want to keep that consistency.

Are you open to making this possible?

### CODE REVIEW

**Comment by kgv** [comment]
Perhaps instead of making entries public we could add support for the "ftl.yaml" extension?
Does this modification solve your case?

**Comment by zicklag** [comment]
That would work for me, as long as you are good with `#[serde(deny_unknown_fields)]` on it. That's the only other change I'd be making for my own loader so far.

Do you want a PR for that instead?

**Comment by kgv** [comment]
> Do you want a PR for that instead?
Yes, that would be cool

**Comment by zicklag** [comment]
\

**Pull request closed without merging**
